# Generated by Django 5.2.6 on 2025-10-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
        migrations.AddField(
            model_name='victim',
            name='verification_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
