# Generated by Django 5.2.6 on 2025-10-04 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0002_delete_emailotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='victim',
            old_name='is_email_verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='verification_token',
        ),
    ]
