# Generated by Django 5.2.7 on 2025-10-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0004_phoneverification_victim_is_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverification',
            name='otp',
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
