# Generated by Django 5.2.7 on 2025-10-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0005_remove_phoneverification_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
